"use client"
import { useEffect, useMemo, useRef, useState } from "react"
import { fmtDate } from "@/lib/data"

/* Catalogue of every Pine script across both machines, generated by
   src/pine_inventory.py on the Mac mini. No compiled-in fallback on purpose:
   it is derived from the script repos, so a hardcoded copy would go stale
   silently and a stale inventory is worse than a missing one. */

type Also = { machine: string; file: string; lines: number; last_modified: string }
type Script = {
  file: string; name: string; kind: string; machine: string; lines: number
  first_tracked: string; last_modified: string; has_file: boolean
  status: string; documented_as?: string; divergent?: boolean; also_on?: Also[]
  panel?: number | null; live?: boolean; tv_name?: string; panel_note?: string
  pine_id?: string | null; in_cloud?: boolean; orphaned?: boolean; orphan_note?: string
  rename_note?: string; github_url?: string; cloud_state?: string
  warning?: string; alert_id?: string; alert_pine_version?: string
  script_version?: string; drift?: string
}
type Counts = {
  total: number; strategies: number; indicators: number; live: number
  with_file: number; divergent: number; panel_map_present: boolean
}
type Catalogue = { scripts: Script[]; counts: Counts; published_at?: string; as_of?: string }

const ACCENT = "#00d4aa", ACCENT2 = "#7c6af7", WARN = "#f59e0b", DOWN = "#ff4d6d"

// Status → colour + label. "undocumented" means no notebook.md entry, which is a
// gap in the record rather than a judgement on the script, so it reads neutral.
const STATUS: Record<string, { c: string; label: string }> = {
  live:            { c: ACCENT,  label: "live" },
  "display-only":  { c: ACCENT2, label: "display only" },
  "observe-only":  { c: WARN,    label: "observe only" },
  "in-development":{ c: WARN,    label: "in development" },
  deleted:         { c: DOWN,    label: "deleted from TV" },
  abandoned:       { c: DOWN,    label: "abandoned" },
  deprecated:      { c: DOWN,    label: "deprecated" },
  documented:      { c: "var(--text2)", label: "documented" },
  undocumented:    { c: "var(--muted)", label: "—" },
}

/* `machine` is the FOLDER a file was found in, not the machine it belongs to:
   "win" = ~/PineScripts, which is the SHARED repo cloned on both machines, so 20 of
   25 rows read "win" for files that live on both. That implied a location split
   which does not exist. Displayed as shared / Mac-only instead — the one real
   distinction, and the one that decides whether the Mac-only files should move into
   the shared repo.

   ⚠️ DISPLAY ONLY. The `machine` field itself is load-bearing: pine_inventory uses it
   for the duplicate-pine_id assertion, which is what caught a duplicated Data Feed
   source on 2026-08-18 and froze the catalogue until it was resolved. Renaming the
   field would break that; renaming the label costs nothing. */
const HOME: Record<string, string> = { win: "shared", mac: "Mac-only" }
const home = (m?: string) => (m ? HOME[m] ?? m : "—")

/* Every row that was not in the TradingView library used to show one "not in cloud"
   pill, which collapsed four unrelated situations into one. A script one paste away
   from working looked identical to one whose source no longer exists anywhere — and
   which of those it is was the actual question being asked of this page.

   `cloud_state` is derived on the Mac (pine_inventory) from Windows' free-text
   `cloud_status`, so the renderer shows a state rather than interpreting prose. The
   tooltip answers the only thing that matters: can I get this back?

   in_cloud and mac_local get NO pill on purpose. in_cloud is the normal case, and
   mac_local is already stated by the Home column — a pill on 17 of 26 rows is noise
   that would bury the four that carry information. */
const CLOUD: Record<string, { label: string; color: string; title: string }> = {
  never_uploaded: { label: "never uploaded", color: ACCENT2,
    title: "The source is here but was never put into TradingView. Recoverable: paste it in as a new script." },
  deleted_from_tv: { label: "deleted from TV", color: DOWN,
    title: "Removed from the TradingView library. The source survives in the repo, so it can be pasted back." },
  superseded: { label: "superseded", color: "var(--muted)",
    title: "Replaced in place by a newer version, which is also listed here." },
  cloud_only: { label: "cloud only", color: WARN,
    title: "Exists in TradingView but there is no local source — nothing to view or archive on this side." },
}

function Pill({ text, color, title }: { text: string; color: string; title?: string }) {
  return (
    <span title={title}
          className="inline-block text-[10px] font-bold px-1.5 py-0.5 rounded whitespace-nowrap"
          style={{ color, border: `1px solid ${color}`, opacity: 0.95 }}>
      {text}
    </span>
  )
}

function Tile({ n, label, color, note }: { n: number | string; label: string; color?: string; note?: string }) {
  return (
    <div className="rounded-xl p-4 flex flex-col gap-1"
         style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
      <p className="text-2xl font-black tabular-nums" style={{ color: color ?? "var(--text)" }}>{n}</p>
      <p className="text-[11px] font-semibold uppercase tracking-widest" style={{ color: "var(--muted)" }}>{label}</p>
      {note && <p className="text-[10px] leading-snug" style={{ color: "var(--muted)" }}>{note}</p>}
    </div>
  )
}

type Filter = "all" | "strategy" | "indicator" | "divergent" | "nofile"

/* Sorting. Each column declares how to READ its own value, so a column sorts by what
   the cell actually shows rather than by a raw field that happens to be near it —
   Status sorts on the rendered label, Home on shared/Mac-only, not on `machine`. */
type SortDir = "asc" | "desc"
const COLS: { label: string; key: string; num?: boolean; get: (s: Script) => string | number | null }[] = [
  { label: "Script",        key: "name",   get: s => (s.tv_name ?? s.name).toLowerCase() },
  { label: "Type",          key: "kind",   get: s => s.kind },
  { label: "Status",        key: "status", get: s => (STATUS[s.live ? "live" : s.status] ?? STATUS.undocumented).label },
  { label: "Panel",         key: "panel",  num: true, get: s => s.panel ?? null },
  { label: "Home",          key: "home",   get: s => (s.machine ? home(s.machine) : null) },
  { label: "First tracked", key: "first",  get: s => s.first_tracked || null },
  { label: "Last change",   key: "last",   get: s => s.last_modified || null },
  { label: "Lines",         key: "lines",  num: true, get: s => s.lines || null },
]

/* ⚠️ Blanks sort LAST in BOTH directions — the empty check returns before the
   direction flip. Otherwise reversing any column parades every row with no panel,
   no file or no date to the top, which is the opposite of what someone reversing a
   sort is looking for, and 6 of 26 rows have at least one blank. */
function sorted(list: Script[], key: string | null, dir: SortDir): Script[] {
  if (!key) return list
  const col = COLS.find(c => c.key === key)
  if (!col) return list
  return [...list].sort((a, b) => {          // copy: never sort the fetched array in place
    const av = col.get(a), bv = col.get(b)
    const ae = av === null || av === undefined || av === ""
    const be = bv === null || bv === undefined || bv === ""
    if (ae && be) return 0
    if (ae) return 1
    if (be) return -1
    const r = col.num
      ? Number(av) - Number(bv)
      : String(av).localeCompare(String(bv))
    return dir === "asc" ? r : -r
  })
}

export default function PineCatalogue() {
  const [cat, setCat] = useState<Catalogue | null>(null)
  const [state, setState] = useState<"loading" | "ok" | "absent">("loading")
  const [filter, setFilter] = useState<Filter>("all")
  const [sortKey, setSortKey] = useState<string | null>(null)
  const [sortDir, setSortDir] = useState<SortDir>("asc")
  /* Per-row state for the Delete button. "asked" is deliberately terminal — the
     row does NOT disappear, because pressing the button changes nothing. It says
     "check Telegram", and the row goes only after the approval and the next
     publish. A button that hid the row optimistically would be claiming an
     authority this page does not have. */
  const [asked, setAsked] = useState<Record<string, string>>({})
  /* Names the Mac already has hidden. The published table lags by up to 5 minutes,
     so without this an approved row sits there looking untouched and the approval
     reads as having failed. Marked in place rather than removed: seeing it struck
     through and labelled is the confirmation — a row that simply vanished would be
     indistinguishable from one that was never there. */
  const [pendingGone, setPendingGone] = useState<Set<string>>(new Set())
  /* Rows already gone as far as the Mac is concerned, so the table stops showing
     them WITHOUT waiting for the 5-minute publish. The published file is the
     table's source, but the hidden list is the authority on what is still listed —
     and this page reads that live, so making it sit out the publish cycle was
     making it wait for information it already had.

     They are struck through first and dropped a few seconds later. Vanishing on
     the instant would remove the only confirmation that the tap landed; that
     confirmation is the entire reason the marking exists. */
  const [dropped, setDropped] = useState<Set<string>>(new Set())
  const DROP_AFTER_MS = 6_000
  const dropTimers = useRef<Record<string, ReturnType<typeof setTimeout>>>({})
  // Poll hard for a minute after a request, then settle. An idle page left open
  // on a second screen should not chatter every 3 seconds indefinitely.
  const fastUntil = useRef(0)
  /* Rows ticked for a bulk request. One approval covers the batch — ten separate
     prompts is how someone ends up tapping Yes without reading them, which is the
     exact failure the confirmation exists to prevent. */
  const [picked, setPicked] = useState<Set<string>>(new Set())
  const toggle = (n: string) =>
    setPicked(p => { const q = new Set(p); q.has(n) ? q.delete(n) : q.add(n); return q })

  const requestBulk = async () => {
    const names = [...picked]
    if (!names.length) return
    fastUntil.current = Date.now() + 60_000
    setAsked(a => ({ ...a, ...Object.fromEntries(names.map(n => [n, "asking"])) }))
    try {
      const r = await fetch("/api/pine-delete", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ scripts: names }),
      })
      const j = await r.json().catch(() => ({}))
      setAsked(a => ({ ...a, ...Object.fromEntries(names.map(n => [n, r.ok ? "sent" : (j?.error || "failed")])) }))
      if (r.ok) setPicked(new Set())
    } catch {
      setAsked(a => ({ ...a, ...Object.fromEntries(names.map(n => [n, "failed"])) }))
    }
  }

  const requestDelete = async (name: string) => {
    fastUntil.current = Date.now() + 60_000     // approval usually lands within seconds
    setAsked(a => ({ ...a, [name]: "asking" }))
    try {
      const r = await fetch("/api/pine-delete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ script: name }),
      })
      const j = await r.json().catch(() => ({}))
      setAsked(a => ({ ...a, [name]: r.ok ? "sent" : (j?.error || "failed") }))
    } catch {
      setAsked(a => ({ ...a, [name]: "failed" }))
    }
  }

  /* Polls, so an approval in Telegram lands here on its own. The page cannot be
     told when you tap Yes — there is no channel from Telegram to a browser — so it
     asks instead. The upstream file is republished at most every 5 minutes, so a
     20s poll is well inside that and still cheap.

     ⚠️ It re-renders only when `published_at` CHANGES. Replacing state on every
     poll would reset the sort, the filter and the per-row "check Telegram" markers
     four times a minute while you are reading the table. */
  useEffect(() => {
    let alive = true
    let stamp = ""
    const load = (first: boolean) =>
      fetch(`/api/pine-catalogue?t=${Date.now()}`, { cache: "no-store" })
        .then(r => r.json())
        .then(j => {
          if (!alive) return
          if (j?.published && j.data?.scripts?.length) {
            const at = String(j.data.published_at ?? "")
            if (first || at !== stamp) {
              stamp = at
              setCat(j.data)
              // A row that has gone stops showing "check Telegram" — the marker has
              // done its job and leaving it would claim a request is still pending.
              const live = new Set(j.data.scripts.map((s: Script) => s.tv_name ?? s.name))
              setAsked(a => Object.fromEntries(Object.entries(a).filter(([k]) => live.has(k))))
            }
            setState("ok")
          } else if (first) setState("absent")
        })
        .catch(() => { if (alive && first) setState("absent") })

    const loadHidden = () =>
      fetch("/api/pine-hidden", { cache: "no-store" })
        .then(r => r.json())
        .then(j => {
          if (!alive || !Array.isArray(j?.hidden)) return
          const hidden = new Set(j.hidden as string[])
          setPendingGone(hidden)
          for (const n of hidden) {
            if (dropTimers.current[n]) continue          // already counting down
            dropTimers.current[n] = setTimeout(() => {
              setDropped(d => new Set(d).add(n))
            }, DROP_AFTER_MS)
          }
          /* ⚠️ A RESTORE has to undo all of this. Without it, /restore would put a
             row back on the Mac while this page kept it invisible for the rest of
             the session — the row would only reappear on a reload, which reads as
             restore being broken. Anything no longer hidden is un-dropped and its
             timer cleared. */
          for (const n of Object.keys(dropTimers.current)) {
            if (!hidden.has(n)) {
              clearTimeout(dropTimers.current[n])
              delete dropTimers.current[n]
            }
          }
          setDropped(d => {
            const next = new Set([...d].filter(n => hidden.has(n)))
            return next.size === d.size ? d : next      // keep identity if unchanged
          })
        })
        .catch(() => {})   // best effort: failing here must only mean "mark nothing"

    load(true); loadHidden()
    let tick = 0
    const id = setInterval(() => {
      tick += 1
      const fast = Date.now() < fastUntil.current
      const slowTick = tick % 7 === 0                    // 7 x 3s = every 21s
      if (fast || slowTick) loadHidden()                 // the live authority: poll it hard
      if (slowTick) load(false)                          // the published file: changes at most every 5 min
    }, 3_000)
    return () => {
      alive = false
      clearInterval(id)
      Object.values(dropTimers.current).forEach(clearTimeout)
    }
  }, [])

  const rows = useMemo(() => {
    if (!cat) return []
    const f = (() => {
      switch (filter) {
        case "strategy":  return cat.scripts.filter(s => s.kind === "strategy")
        case "indicator": return cat.scripts.filter(s => s.kind === "indicator")
        case "divergent": return cat.scripts.filter(s => s.divergent)
        case "nofile":    return cat.scripts.filter(s => !s.has_file)
        default:          return cat.scripts
      }
    })()
    // Sort applies WITHIN the current filter, not across it.
    return sorted(f.filter(s => !dropped.has(s.tv_name ?? s.name)), sortKey, sortDir)
  }, [cat, filter, sortKey, sortDir, dropped])

  /* Three states per column: asc → desc → back to the published order. The third is
     the point — the default (live first, then panel, then name) is curated and
     genuinely useful, and without a way back you would have to reload the page to
     recover it. */
  const clickCol = (key: string) => {
    if (sortKey !== key) { setSortKey(key); setSortDir("asc"); return }
    if (sortDir === "asc") { setSortDir("desc"); return }
    setSortKey(null); setSortDir("asc")
  }

  if (state === "loading") {
    return <div className="rounded-xl p-5 animate-pulse" style={{ background: "var(--surface)", border: "1px solid var(--border)", height: 120 }} />
  }
  if (state === "absent" || !cat) {
    return (
      <div className="rounded-xl p-5" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
        <h2 className="text-sm font-bold">Pine script catalogue</h2>
        <p className="text-xs mt-2" style={{ color: "var(--muted)" }}>
          Not published yet. The catalogue is generated on the Mac mini and appears here on the next
          publish cycle.
        </p>
      </div>
    )
  }

  const c = cat.counts
  /* Counts come from the rows actually LISTED, not from the payload, or a dropped
     row would still be counted and the tiles would contradict the table. */
  const listed = cat.scripts.filter(s => !dropped.has(s.tv_name ?? s.name))
  const FILTERS: { k: Filter; label: string; n: number }[] = [
    { k: "all",       label: "All",           n: listed.length },
    { k: "strategy",  label: "Strategies",    n: listed.filter(s => s.kind === "strategy").length },
    { k: "indicator", label: "Indicators",    n: listed.filter(s => s.kind === "indicator").length },
    { k: "divergent", label: "Diverged",      n: listed.filter(s => s.divergent).length },
    { k: "nofile",    label: "No file left",  n: listed.filter(s => !s.has_file).length },
  ]

  return (
    <div className="flex flex-col gap-4">
      <div>
        <h2 className="text-lg font-black tracking-tight">Pine script catalogue</h2>
        <p className="text-xs mt-1" style={{ color: "var(--muted)" }}>
          Every script across both machines, including the ones deleted from TradingView — those are
          the record of what was tried. Generated from the two script repos and the strategy log.
        </p>
      </div>

      <div className="grid gap-3 grid-cols-2 sm:grid-cols-4">
        <Tile n={listed.length} label="scripts" />
        <Tile n={`${listed.filter(s => s.kind === "strategy").length} / ${listed.filter(s => s.kind === "indicator").length}`} label="strategy / indicator" color={ACCENT2} />
        <Tile n={listed.filter(s => s.divergent).length} label="diverged" color={c.divergent ? WARN : undefined}
              note={c.divergent ? "same script, different content per machine" : undefined} />
        <Tile n={c.panel_map_present ? listed.filter(s => s.live).length : "—"} label="live on a panel"
              color={c.panel_map_present ? ACCENT : "var(--muted)"}
              note={c.panel_map_present ? undefined : "panel map not supplied yet"} />
      </div>

      {!c.panel_map_present && (
        <p className="text-[11px] leading-relaxed rounded-lg p-3"
           style={{ background: "rgba(245,158,11,0.06)", border: "1px solid var(--border)", borderLeft: `3px solid ${WARN}`, color: "var(--text2)" }}>
          <b>Panel assignments are not filled in yet</b>, so every row reads &quot;unknown&quot; rather than
          &quot;not live&quot;. Which panel a script sits on is the one fact neither repo contains — only the
          Windows machine can see the chart layout, and it supplies it separately.
        </p>
      )}

      {/* Operational warnings that no amount of reading the repos would reveal.
          Rendered above the table because the Data Feed one is a delete-this-and-
          the-bar-feed-dies trap, and it is counter-intuitive in the dangerous
          direction: the reassuring name is on the inert script. */}
      {/* ⚠️ The label was hardcoded "— live critical." — written when the Data Feed was the only
          warning, and FALSE the moment a second arrived: MNQ ORB is retired, and its warning is
          "never commit this", not "don't delete this". The name is emphasised and the warning
          speaks for itself, so the banner cannot assert a severity the value never claimed.
          Keyed on name rather than file: a warning row need not have a working file, which is
          exactly the MNQ ORB case. */}
      {cat.scripts.filter(s => s.warning).map(s => (
        <div key={`w-${s.tv_name ?? s.name}`} className="text-[11px] leading-relaxed rounded-lg p-3"
             style={{ background: "rgba(255,77,109,0.07)", border: "1px solid var(--border)", borderLeft: `3px solid ${DOWN}`, color: "var(--text2)" }}>
          <p><b style={{ color: DOWN }}>{s.tv_name ?? s.name}</b> {s.warning}</p>
          {s.rename_note && <p className="mt-1.5">{s.rename_note}</p>}
          {s.drift && (
            <p className="mt-1.5">
              <b>Alert {s.alert_id} is pinned at v{s.alert_pine_version}, the script is at
              v{s.script_version}.</b> {s.drift}
            </p>
          )}
        </div>
      ))}

      <div className="flex gap-1.5 flex-wrap">
        {FILTERS.map(f => (
          <button key={f.k} onClick={() => setFilter(f.k)}
                  className="px-2.5 py-1 rounded text-xs font-semibold transition-colors"
                  style={{
                    background: filter === f.k ? "var(--accent2)" : "var(--surface2)",
                    color: filter === f.k ? "#fff" : "var(--text2)",
                    border: "1px solid var(--border)",
                  }}>
            {f.label} <span className="tabular-nums opacity-70">{f.n}</span>
          </button>
        ))}
      </div>

      {picked.size > 0 && (
        <div className="flex items-center gap-3 rounded-lg p-3 text-xs"
             style={{ background: "var(--surface2)", border: "1px solid var(--border)" }}>
          <span style={{ color: "var(--text2)" }}>
            <b>{picked.size}</b> selected
          </span>
          <button type="button" onClick={requestBulk}
                  className="px-2.5 py-1 rounded font-semibold"
                  style={{ color: DOWN, border: `1px solid ${DOWN}` }}>
            Request removal of {picked.size}
          </button>
          <button type="button" onClick={() => setPicked(new Set())}
                  className="px-2 py-1 rounded" style={{ color: "var(--muted)" }}>
            Clear
          </button>
          <span style={{ color: "var(--muted)" }}>
            One Telegram message, one approval for all of them.
          </span>
        </div>
      )}

      <div className="rounded-xl scroll-x" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
        <table className="w-full text-xs" style={{ borderCollapse: "collapse" }}>
          <thead>
            <tr style={{ color: "var(--muted)" }}>
              <th className="px-2 py-2" style={{ borderBottom: "1px solid var(--border)" }} />
              {COLS.map((col, i) => {
                const active = sortKey === col.key
                return (
                  <th key={col.key}
                      aria-sort={active ? (sortDir === "asc" ? "ascending" : "descending") : "none"}
                      className={`px-3 py-2 font-semibold whitespace-nowrap ${i > 2 ? "text-right" : "text-left"}`}
                      style={{ borderBottom: "1px solid var(--border)" }}>
                    <button type="button" onClick={() => clickCol(col.key)}
                            title={active
                              ? (sortDir === "asc" ? "Sorted ascending — click for descending"
                                                   : "Sorted descending — click to restore the default order")
                              : `Sort by ${col.label}`}
                            className="inline-flex items-center gap-1 hover:underline"
                            style={{ color: active ? ACCENT : "inherit" }}>
                      {col.label}
                      <span aria-hidden="true" style={{ opacity: active ? 1 : 0.25 }}>
                        {active ? (sortDir === "asc" ? "\u25b2" : "\u25bc") : "\u25b4"}
                      </span>
                    </button>
                  </th>
                )
              })}
              <th className="px-3 py-2 font-semibold text-right whitespace-nowrap"
                  style={{ borderBottom: "1px solid var(--border)" }}>Remove</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((s, i) => {
              const st = STATUS[s.live ? "live" : s.status] ?? STATUS.undocumented
              const gone = pendingGone.has(s.tv_name ?? s.name)
              return (
                <tr key={`${s.name}-${i}`} style={{ borderBottom: "1px solid var(--border)" }}>
                  <td className="px-2 py-2 align-top">
                    {/* No tick on a row already gone — it cannot be requested again. */}
                    {!gone && (
                      // The <label> is the tap target, not the box. A bare native
                      // checkbox is ~14px, and this one starts a REMOVAL request —
                      // a fat-finger miss here costs more than an annoyance.
                      // Clicking the label toggles the nested input for free.
                      <label className="flex items-center justify-center -m-1 p-1 cursor-pointer"
                             style={{ minWidth: 40, minHeight: 40 }}>
                        <input type="checkbox" aria-label={`Select ${s.tv_name ?? s.name}`}
                               className="w-4 h-4 cursor-pointer"
                               checked={picked.has(s.tv_name ?? s.name)}
                               onChange={() => toggle(s.tv_name ?? s.name)} />
                      </label>
                    )}
                  </td>
                  <td className="px-3 py-2">
                    <div className="font-semibold flex items-center gap-2"
                         style={{ color: gone ? "var(--muted)" : "var(--text)",
                                  textDecoration: gone ? "line-through" : undefined }}>
                      {s.tv_name ?? s.name}
                      {gone && <Pill text="removed" color={DOWN}
                                     title="Approved in Telegram. It disappears from this table at the next publish, within about 5 minutes." />}
                    </div>
                    {/* The filename links to its source, not the title: the title is
                        TradingView's name and the link is a file in a repo, so the
                        filename is the thing that actually corresponds. Only 19 of 31
                        rows carry a URL — the rest have no source in that repo. */}
                    {/* ⚠️ Underline + an explicit ↗, NOT colour alone. The first version
                        cued the link only by tinting a 10px monospace filename teal, and
                        the owner reported seeing no link at all on a page that was
                        rendering them correctly — at that size a hue shift is not a
                        visible affordance, and colour-only also fails anyone who cannot
                        separate the two hues. The larger tap target matters on a phone. */}
                    <div className="text-[10px] font-mono" style={{ color: "var(--muted)" }}>
                      {s.github_url ? (
                        <a href={s.github_url} target="_blank" rel="noopener noreferrer"
                           title="Open the source in the PineScripts repo — private, so it needs repo access"
                           className="inline-flex items-center gap-1 underline decoration-dotted underline-offset-2 py-0.5"
                           style={{ color: ACCENT, textDecorationColor: ACCENT }}>
                          {s.file}
                          <span aria-hidden="true" className="not-italic">↗</span>
                          <span className="sr-only"> (opens source in a new tab)</span>
                        </a>
                      ) : (
                        s.file || "no working file"
                      )}
                    </div>
                    {s.orphaned ? (
                      <div className="mt-1"><Pill text="orphaned study" color={WARN}
                            title={s.orphan_note ?? "Live on a pane with no library script behind it"} /></div>
                    ) : s.cloud_state && CLOUD[s.cloud_state] ? (
                      <div className="mt-1">
                        <Pill text={CLOUD[s.cloud_state].label}
                              color={CLOUD[s.cloud_state].color}
                              title={CLOUD[s.cloud_state].title} />
                      </div>
                    ) : null}
                    {/* Windows owns these values (only it can see the chart layout); this side
                        renders them VERBATIM and does not parse them for meaning. 10 rows carry
                        one and all were invisible until 2026-08-18 — including "LIVE CRITICAL:
                        feeds bars.jsonl" and the MNQ ORB exclusion, where a blank link column
                        read as a gap to fill rather than a file that must never be committed.
                        A note needing more force belongs in `warning`, which already renders as
                        a banner above the table — that choice is Windows', not a keyword match
                        here. Width-capped so one long note cannot stretch the column. */}
                    {s.panel_note && (
                      <div className="mt-1 text-[10px] leading-snug max-w-[26rem]"
                           style={{ color: "var(--muted)" }}>
                        {s.panel_note}
                      </div>
                    )}
                    {s.divergent && s.also_on?.[0] && (
                      <div className="mt-1">
                        <Pill text="diverged" color={WARN}
                              title={`Also on ${home(s.also_on[0].machine)} as ${s.also_on[0].file} (${s.also_on[0].lines} lines, ${s.also_on[0].last_modified}) — different content`} />
                      </div>
                    )}
                  </td>
                  <td className="px-3 py-2">
                    <Pill text={s.kind} color={s.kind === "strategy" ? ACCENT2 : "var(--text2)"} />
                  </td>
                  <td className="px-3 py-2"><Pill text={st.label} color={st.c} /></td>
                  <td className="px-3 py-2 text-right tabular-nums" style={{ color: s.panel ? "var(--text)" : "var(--muted)" }}>
                    {s.panel ?? "unknown"}
                  </td>
                  <td className="px-3 py-2 text-right font-mono" style={{ color: "var(--muted)" }}>
                    {home(s.machine)}
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums" style={{ color: "var(--muted)" }}>
                    {s.first_tracked || "—"}
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums" style={{ color: "var(--muted)" }}>
                    {s.last_modified || "—"}
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums" style={{ color: "var(--muted)" }}>
                    {s.lines || "—"}
                  </td>
                  <td className="px-3 py-2 text-right whitespace-nowrap">
                    {(() => {
                      const name = s.tv_name ?? s.name
                      if (gone) return <span className="text-[10px]" style={{ color: DOWN }}>removed</span>
                      const st = asked[name]
                      if (st === "sent") return <span className="text-[10px]" style={{ color: ACCENT }}>check Telegram</span>
                      if (st === "asking") return <span className="text-[10px]" style={{ color: "var(--muted)" }}>asking…</span>
                      if (st) return <span className="text-[10px]" title={st} style={{ color: DOWN }}>{st}</span>
                      return (
                        <button type="button" onClick={() => requestDelete(name)}
                                title="Asks for approval in Telegram. Nothing is removed until you tap Yes there."
                                className="text-[10px] font-bold px-1.5 py-0.5 rounded"
                                style={{ color: "var(--muted)", border: "1px solid var(--border)" }}>
                          Remove
                        </button>
                      )
                    })()}
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      <p className="text-[11px] leading-relaxed" style={{ color: "var(--muted)" }}>
        <b>Panel data is a snapshot{cat.as_of ? ` taken ${fmtDate(cat.as_of.slice(0, 10))}` : ""}, not live.</b>{" "}
        Rows keyed on TradingView&apos;s <span className="font-mono">pine_id</span>, which survives renames
        and is fresh on every copy — names are not usable as keys, since duplicate-before-editing leaves
        20 library scripts sharing only 13 titles. The pill on a row says what happened to it in TradingView, and the tooltip says
        whether it can be recovered: <b>never uploaded</b> and <b>deleted from TV</b> both still
        have their source here and paste back; <b>cloud only</b> does not, so there is nothing on
        this side to view. Rows with no pill are either in the library normally or Mac-only,
        which the Home column already states.{" "}
        <b>Orphaned study</b> means it is running on a pane with no library script behind it — saved
        once, then deleted from the library while the chart instance stayed attached. So no
        <span className="font-mono"> pine_id</span> does <i>not</i> mean not deployed: one of these is
        live right now and cannot be recovered from the library.{" "}
        <b>An underlined filename marked ↗ links to its source</b> in the PineScripts repo, which is
        private — the link needs repo access to open, and a plain filename has no source there at all
        (local to one machine, or deleted).{" "}
        <b>Tick several rows</b> to request them together — one Telegram message listing all of them and one approval, rather than a prompt per script. {" "}<b>Approve in Telegram and the row goes within a few seconds</b> — struck through and marked <span style={{ color: "#ff4d6d" }}>removed</span> first, so you can see the tap landed, then dropped from the table. It does not wait for the underlying file, which catches up separately.{" "}
        <b>This table refreshes itself every 20 seconds</b>, so a removal you approve in Telegram disappears on its own — though the underlying file is only republished every 5 minutes, so give it a few minutes. Your sort and filter are kept when it updates.{" "}
        <b>Remove asks, it does not act.</b> It sends a request to Telegram and the row stays until you approve it there and the next publish runs — this page has no login, so it cannot be allowed to remove anything on its own. Nothing is deleted either way: the row is hidden, the file is untouched, and TradingView is unchanged.{" "}
        <b>First tracked is not a creation date.</b> It is the day the file entered version control,
        and several scripts share one date because that is when the repo itself was created — the
        scripts are older. <b>No working file</b> means the script is recorded in the strategy log but
        has no source file left, usually because it was deleted from TradingView.
      </p>
    </div>
  )
}
