"use client"
import { useEffect, useMemo, useState } from "react"
import { fmtDate } from "@/lib/data"

/* Catalogue of every Pine script across both machines, generated by
   src/pine_inventory.py on the Mac mini. No compiled-in fallback on purpose:
   it is derived from the script repos, so a hardcoded copy would go stale
   silently and a stale inventory is worse than a missing one. */

type Also = { machine: string; file: string; lines: number; last_modified: string }
type Script = {
  file: string; name: string; kind: string; machine: string; lines: number
  first_tracked: string; last_modified: string; has_file: boolean
  status: string; documented_as?: string; divergent?: boolean; also_on?: Also[]
  panel?: number | null; live?: boolean; tv_name?: string; panel_note?: string
  pine_id?: string | null; in_cloud?: boolean; orphaned?: boolean; orphan_note?: string
  rename_note?: string; github_url?: string
  warning?: string; alert_id?: string; alert_pine_version?: string
  script_version?: string; drift?: string
}
type Counts = {
  total: number; strategies: number; indicators: number; live: number
  with_file: number; divergent: number; panel_map_present: boolean
}
type Catalogue = { scripts: Script[]; counts: Counts; published_at?: string; as_of?: string }

const ACCENT = "#00d4aa", ACCENT2 = "#7c6af7", WARN = "#f59e0b", DOWN = "#ff4d6d"

// Status → colour + label. "undocumented" means no notebook.md entry, which is a
// gap in the record rather than a judgement on the script, so it reads neutral.
const STATUS: Record<string, { c: string; label: string }> = {
  live:            { c: ACCENT,  label: "live" },
  "display-only":  { c: ACCENT2, label: "display only" },
  "observe-only":  { c: WARN,    label: "observe only" },
  "in-development":{ c: WARN,    label: "in development" },
  deleted:         { c: DOWN,    label: "deleted from TV" },
  abandoned:       { c: DOWN,    label: "abandoned" },
  deprecated:      { c: DOWN,    label: "deprecated" },
  documented:      { c: "var(--text2)", label: "documented" },
  undocumented:    { c: "var(--muted)", label: "—" },
}

function Pill({ text, color, title }: { text: string; color: string; title?: string }) {
  return (
    <span title={title}
          className="inline-block text-[10px] font-bold px-1.5 py-0.5 rounded whitespace-nowrap"
          style={{ color, border: `1px solid ${color}`, opacity: 0.95 }}>
      {text}
    </span>
  )
}

function Tile({ n, label, color, note }: { n: number | string; label: string; color?: string; note?: string }) {
  return (
    <div className="rounded-xl p-4 flex flex-col gap-1"
         style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
      <p className="text-2xl font-black tabular-nums" style={{ color: color ?? "var(--text)" }}>{n}</p>
      <p className="text-[11px] font-semibold uppercase tracking-widest" style={{ color: "var(--muted)" }}>{label}</p>
      {note && <p className="text-[10px] leading-snug" style={{ color: "var(--muted)" }}>{note}</p>}
    </div>
  )
}

type Filter = "all" | "strategy" | "indicator" | "divergent" | "nofile"

export default function PineCatalogue() {
  const [cat, setCat] = useState<Catalogue | null>(null)
  const [state, setState] = useState<"loading" | "ok" | "absent">("loading")
  const [filter, setFilter] = useState<Filter>("all")

  useEffect(() => {
    let alive = true
    fetch(`/api/pine-catalogue?t=${Date.now()}`)
      .then(r => r.json())
      .then(j => {
        if (!alive) return
        if (j?.published && j.data?.scripts?.length) { setCat(j.data); setState("ok") }
        else setState("absent")
      })
      .catch(() => { if (alive) setState("absent") })
    return () => { alive = false }
  }, [])

  const rows = useMemo(() => {
    if (!cat) return []
    switch (filter) {
      case "strategy":  return cat.scripts.filter(s => s.kind === "strategy")
      case "indicator": return cat.scripts.filter(s => s.kind === "indicator")
      case "divergent": return cat.scripts.filter(s => s.divergent)
      case "nofile":    return cat.scripts.filter(s => !s.has_file)
      default:          return cat.scripts
    }
  }, [cat, filter])

  if (state === "loading") {
    return <div className="rounded-xl p-5 animate-pulse" style={{ background: "var(--surface)", border: "1px solid var(--border)", height: 120 }} />
  }
  if (state === "absent" || !cat) {
    return (
      <div className="rounded-xl p-5" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
        <h2 className="text-sm font-bold">Pine script catalogue</h2>
        <p className="text-xs mt-2" style={{ color: "var(--muted)" }}>
          Not published yet. The catalogue is generated on the Mac mini and appears here on the next
          publish cycle.
        </p>
      </div>
    )
  }

  const c = cat.counts
  const FILTERS: { k: Filter; label: string; n: number }[] = [
    { k: "all",       label: "All",           n: c.total },
    { k: "strategy",  label: "Strategies",    n: c.strategies },
    { k: "indicator", label: "Indicators",    n: c.indicators },
    { k: "divergent", label: "Diverged",      n: c.divergent },
    { k: "nofile",    label: "No file left",  n: c.total - c.with_file },
  ]

  return (
    <div className="flex flex-col gap-4">
      <div>
        <h2 className="text-lg font-black tracking-tight">Pine script catalogue</h2>
        <p className="text-xs mt-1" style={{ color: "var(--muted)" }}>
          Every script across both machines, including the ones deleted from TradingView — those are
          the record of what was tried. Generated from the two script repos and the strategy log.
        </p>
      </div>

      <div className="grid gap-3 grid-cols-2 sm:grid-cols-4">
        <Tile n={c.total} label="scripts" />
        <Tile n={`${c.strategies} / ${c.indicators}`} label="strategy / indicator" color={ACCENT2} />
        <Tile n={c.divergent} label="diverged" color={c.divergent ? WARN : undefined}
              note={c.divergent ? "same script, different content per machine" : undefined} />
        <Tile n={c.panel_map_present ? c.live : "—"} label="live on a panel"
              color={c.panel_map_present ? ACCENT : "var(--muted)"}
              note={c.panel_map_present ? undefined : "panel map not supplied yet"} />
      </div>

      {!c.panel_map_present && (
        <p className="text-[11px] leading-relaxed rounded-lg p-3"
           style={{ background: "rgba(245,158,11,0.06)", border: "1px solid var(--border)", borderLeft: `3px solid ${WARN}`, color: "var(--text2)" }}>
          <b>Panel assignments are not filled in yet</b>, so every row reads &quot;unknown&quot; rather than
          &quot;not live&quot;. Which panel a script sits on is the one fact neither repo contains — only the
          Windows machine can see the chart layout, and it supplies it separately.
        </p>
      )}

      {/* Operational warnings that no amount of reading the repos would reveal.
          Rendered above the table because the Data Feed one is a delete-this-and-
          the-bar-feed-dies trap, and it is counter-intuitive in the dangerous
          direction: the reassuring name is on the inert script. */}
      {cat.scripts.filter(s => s.warning).map(s => (
        <div key={`w-${s.file}`} className="text-[11px] leading-relaxed rounded-lg p-3"
             style={{ background: "rgba(255,77,109,0.07)", border: "1px solid var(--border)", borderLeft: `3px solid ${DOWN}`, color: "var(--text2)" }}>
          <p><b style={{ color: DOWN }}>{s.tv_name ?? s.name} — live critical.</b> {s.warning}</p>
          {s.rename_note && <p className="mt-1.5">{s.rename_note}</p>}
          {s.drift && (
            <p className="mt-1.5">
              <b>Alert {s.alert_id} is pinned at v{s.alert_pine_version}, the script is at
              v{s.script_version}.</b> {s.drift}
            </p>
          )}
        </div>
      ))}

      <div className="flex gap-1.5 flex-wrap">
        {FILTERS.map(f => (
          <button key={f.k} onClick={() => setFilter(f.k)}
                  className="px-2.5 py-1 rounded text-xs font-semibold transition-colors"
                  style={{
                    background: filter === f.k ? "var(--accent2)" : "var(--surface2)",
                    color: filter === f.k ? "#fff" : "var(--text2)",
                    border: "1px solid var(--border)",
                  }}>
            {f.label} <span className="tabular-nums opacity-70">{f.n}</span>
          </button>
        ))}
      </div>

      <div className="rounded-xl overflow-x-auto" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
        <table className="w-full text-xs" style={{ borderCollapse: "collapse" }}>
          <thead>
            <tr style={{ color: "var(--muted)" }}>
              {["Script", "Type", "Status", "Panel", "Where", "First tracked", "Last change", "Lines"].map((h, i) => (
                <th key={h} className={`px-3 py-2 font-semibold whitespace-nowrap ${i > 2 ? "text-right" : "text-left"}`}
                    style={{ borderBottom: "1px solid var(--border)" }}>
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((s, i) => {
              const st = STATUS[s.live ? "live" : s.status] ?? STATUS.undocumented
              return (
                <tr key={`${s.name}-${i}`} style={{ borderBottom: "1px solid var(--border)" }}>
                  <td className="px-3 py-2">
                    <div className="font-semibold" style={{ color: "var(--text)" }}>{s.tv_name ?? s.name}</div>
                    {/* The filename links to its source, not the title: the title is
                        TradingView's name and the link is a file in a repo, so the
                        filename is the thing that actually corresponds. Only 19 of 31
                        rows carry a URL — the rest have no source in that repo. */}
                    {/* ⚠️ Underline + an explicit ↗, NOT colour alone. The first version
                        cued the link only by tinting a 10px monospace filename teal, and
                        the owner reported seeing no link at all on a page that was
                        rendering them correctly — at that size a hue shift is not a
                        visible affordance, and colour-only also fails anyone who cannot
                        separate the two hues. The larger tap target matters on a phone. */}
                    <div className="text-[10px] font-mono" style={{ color: "var(--muted)" }}>
                      {s.github_url ? (
                        <a href={s.github_url} target="_blank" rel="noopener noreferrer"
                           title="Open the source in the PineScripts repo — private, so it needs repo access"
                           className="inline-flex items-center gap-1 underline decoration-dotted underline-offset-2 py-0.5"
                           style={{ color: ACCENT, textDecorationColor: ACCENT }}>
                          {s.file}
                          <span aria-hidden="true" className="not-italic">↗</span>
                          <span className="sr-only"> (opens source in a new tab)</span>
                        </a>
                      ) : (
                        s.file || "no working file"
                      )}
                    </div>
                    {s.orphaned ? (
                      <div className="mt-1"><Pill text="orphaned study" color={WARN}
                            title={s.orphan_note ?? "Live on a pane with no library script behind it"} /></div>
                    ) : s.in_cloud === false && (
                      <div className="mt-1"><Pill text="not in cloud" color="var(--muted)"
                            title="No TradingView pine_id — local-only or archived, not missing data" /></div>
                    )}
                    {/* Windows owns these values (only it can see the chart layout); this side
                        renders them VERBATIM and does not parse them for meaning. 10 rows carry
                        one and all were invisible until 2026-08-18 — including "LIVE CRITICAL:
                        feeds bars.jsonl" and the MNQ ORB exclusion, where a blank link column
                        read as a gap to fill rather than a file that must never be committed.
                        A note needing more force belongs in `warning`, which already renders as
                        a banner above the table — that choice is Windows', not a keyword match
                        here. Width-capped so one long note cannot stretch the column. */}
                    {s.panel_note && (
                      <div className="mt-1 text-[10px] leading-snug max-w-[26rem]"
                           style={{ color: "var(--muted)" }}>
                        {s.panel_note}
                      </div>
                    )}
                    {s.divergent && s.also_on?.[0] && (
                      <div className="mt-1">
                        <Pill text="diverged" color={WARN}
                              title={`Also on ${s.also_on[0].machine} as ${s.also_on[0].file} (${s.also_on[0].lines} lines, ${s.also_on[0].last_modified}) — different content`} />
                      </div>
                    )}
                  </td>
                  <td className="px-3 py-2">
                    <Pill text={s.kind} color={s.kind === "strategy" ? ACCENT2 : "var(--text2)"} />
                  </td>
                  <td className="px-3 py-2"><Pill text={st.label} color={st.c} /></td>
                  <td className="px-3 py-2 text-right tabular-nums" style={{ color: s.panel ? "var(--text)" : "var(--muted)" }}>
                    {s.panel ?? "unknown"}
                  </td>
                  <td className="px-3 py-2 text-right font-mono" style={{ color: "var(--muted)" }}>
                    {s.machine || "—"}
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums" style={{ color: "var(--muted)" }}>
                    {s.first_tracked || "—"}
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums" style={{ color: "var(--muted)" }}>
                    {s.last_modified || "—"}
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums" style={{ color: "var(--muted)" }}>
                    {s.lines || "—"}
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      <p className="text-[11px] leading-relaxed" style={{ color: "var(--muted)" }}>
        <b>Panel data is a snapshot{cat.as_of ? ` taken ${fmtDate(cat.as_of.slice(0, 10))}` : ""}, not live.</b>{" "}
        Rows keyed on TradingView&apos;s <span className="font-mono">pine_id</span>, which survives renames
        and is fresh on every copy — names are not usable as keys, since duplicate-before-editing leaves
        20 library scripts sharing only 13 titles. <b>Not in cloud</b> means the script has no id because
        it is local-only or archived, which is a state rather than missing data.{" "}
        <b>Orphaned study</b> means it is running on a pane with no library script behind it — saved
        once, then deleted from the library while the chart instance stayed attached. So no
        <span className="font-mono"> pine_id</span> does <i>not</i> mean not deployed: one of these is
        live right now and cannot be recovered from the library.{" "}
        <b>An underlined filename marked ↗ links to its source</b> in the PineScripts repo, which is
        private — the link needs repo access to open, and a plain filename has no source there at all
        (local to one machine, or deleted).{" "}
        <b>First tracked is not a creation date.</b> It is the day the file entered version control,
        and several scripts share one date because that is when the repo itself was created — the
        scripts are older. <b>No working file</b> means the script is recorded in the strategy log but
        has no source file left, usually because it was deleted from TradingView.
      </p>
    </div>
  )
}
